# Generated by Django 2.2.3 on 2019-07-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasureHunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='terrain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
