# Generated by Django 2.2.3 on 2019-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasureHunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='coord_x',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='coord_y',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='elevation',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='terrain',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
