# Generated by Django 2.2.3 on 2019-07-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasureHunt', '0002_auto_20190731_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
